Search.appendIndex(
    [
                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\AccessTokenHandler",
            "name": "AccessTokenHandler",
            "summary": "Manages\u0020the\u0020access\u0020token\u0020that\u0020is\u0020needed\u0020to\u0020authenticate\u0020the\u0020Google\u0020Firebase\u0020API\u0020calls.",
            "url": "classes/Mve-FcmPhp-Models-AccessTokenHandler.html"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\AccessTokenHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-AccessTokenHandler.html#method___construct"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\AccessTokenHandler\u003A\u003AgetToken\u0028\u0029",
            "name": "getToken",
            "summary": "Returns\u0020a\u0020non\u0020expired\u0020access\u0020token\u0020from\u0020the\u0020cache,\u0020or\u0020if\u0020there\u0020isn\u0027t\u0020one,\u0020from\u0020the\u0020Google\u0020API\u0020and\u0020stores\u0020this\u0020one\u0020in\u0020the\u0020cache.",
            "url": "classes/Mve-FcmPhp-Models-AccessTokenHandler.html#method_getToken"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\AccessTokenHandler\u003A\u003AgetProjectId\u0028\u0029",
            "name": "getProjectId",
            "summary": "Returns\u0020the\u0020project\u0020ID.",
            "url": "classes/Mve-FcmPhp-Models-AccessTokenHandler.html#method_getProjectId"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\AccessTokenHandler\u003A\u003ACACHE_ACCESS_TOKEN_NAME",
            "name": "CACHE_ACCESS_TOKEN_NAME",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-AccessTokenHandler.html#constant_CACHE_ACCESS_TOKEN_NAME"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\AccessTokenHandler\u003A\u003ASCOPE_FIREBASE_MESSAGING",
            "name": "SCOPE_FIREBASE_MESSAGING",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-AccessTokenHandler.html#constant_SCOPE_FIREBASE_MESSAGING"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\AccessTokenHandler\u003A\u003A\u0024fetchAuthToken",
            "name": "fetchAuthToken",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-AccessTokenHandler.html#property_fetchAuthToken"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\AccessTokenHandler\u003A\u003A\u0024projectId",
            "name": "projectId",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-AccessTokenHandler.html#property_projectId"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\AccessTokenHandler\u003A\u003A\u0024cache",
            "name": "cache",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-AccessTokenHandler.html#property_cache"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\AccessTokenHandler\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-AccessTokenHandler.html#property_logger"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\CacheInterface",
            "name": "CacheInterface",
            "summary": "Interface\u0020for\u0020simple\u0020caching\u0020functionality.\u0020Used\u0020to\u0020store\u0020access\u0020tokens.",
            "url": "classes/Mve-FcmPhp-Models-CacheInterface.html"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\CacheInterface\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Gets\u0020a\u0020key\u0020from\u0020the\u0020cache.",
            "url": "classes/Mve-FcmPhp-Models-CacheInterface.html#method_get"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\CacheInterface\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "Puts\u0020a\u0020key\u0020into\u0020the\u0020cache.",
            "url": "classes/Mve-FcmPhp-Models-CacheInterface.html#method_put"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\CacheInterface\u003A\u003Aflush\u0028\u0029",
            "name": "flush",
            "summary": "Removes\u0020all\u0020items\u0020from\u0020the\u0020cache.",
            "url": "classes/Mve-FcmPhp-Models-CacheInterface.html#method_flush"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\CacheInterface\u003A\u003Aforget\u0028\u0029",
            "name": "forget",
            "summary": "Removes\u0020an\u0020item\u0020from\u0020the\u0020cache.",
            "url": "classes/Mve-FcmPhp-Models-CacheInterface.html#method_forget"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\FcmError",
            "name": "FcmError",
            "summary": "An\u0020error\u0020with\u0020specific\u0020Google\u0020Firebase\u0020information.",
            "url": "classes/Mve-FcmPhp-Models-FcmError.html"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\FcmError\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-FcmError.html#method___construct"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\FcmError\u003A\u003AERROR_UNKNOWN",
            "name": "ERROR_UNKNOWN",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-FcmError.html#constant_ERROR_UNKNOWN"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\FcmError\u003A\u003AERROR_UNAUTHENTICATED",
            "name": "ERROR_UNAUTHENTICATED",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-FcmError.html#constant_ERROR_UNAUTHENTICATED"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\FcmError\u003A\u003AERROR_NOT_FOUND",
            "name": "ERROR_NOT_FOUND",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-FcmError.html#constant_ERROR_NOT_FOUND"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\FcmError\u003A\u003AERROR_UNREGISTERED",
            "name": "ERROR_UNREGISTERED",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-FcmError.html#constant_ERROR_UNREGISTERED"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\FcmError\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-FcmError.html#property_code"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\FcmError\u003A\u003A\u0024error",
            "name": "error",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-FcmError.html#property_error"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\FcmError\u003A\u003A\u0024message",
            "name": "message",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-FcmError.html#property_message"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\FcmError\u003A\u003A\u0024content",
            "name": "content",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-FcmError.html#property_content"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\FcmException",
            "name": "FcmException",
            "summary": "Exception\u0020with\u0020specific\u0020information\u0020that\u0020is\u0020from\u0020the\u0020Google\u0020Firebase\u0020API.",
            "url": "classes/Mve-FcmPhp-Models-FcmException.html"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\FcmException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-FcmException.html#method___construct"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\FcmException\u003A\u003A\u0024fcmError",
            "name": "fcmError",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-FcmException.html#property_fcmError"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\FcmException\u003A\u003A\u0024sendAllResult",
            "name": "sendAllResult",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-FcmException.html#property_sendAllResult"
        },                {
            "fqsen": "\\App\\Models\\LaravelCache",
            "name": "LaravelCache",
            "summary": "",
            "url": "classes/App-Models-LaravelCache.html"
        },                {
            "fqsen": "\\App\\Models\\LaravelCache\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Gets\u0020a\u0020key\u0020from\u0020the\u0020cache.",
            "url": "classes/App-Models-LaravelCache.html#method_get"
        },                {
            "fqsen": "\\App\\Models\\LaravelCache\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "Puts\u0020a\u0020key\u0020into\u0020the\u0020cache.",
            "url": "classes/App-Models-LaravelCache.html#method_put"
        },                {
            "fqsen": "\\App\\Models\\LaravelCache\u003A\u003Aforget\u0028\u0029",
            "name": "forget",
            "summary": "Removes\u0020an\u0020item\u0020from\u0020the\u0020cache.",
            "url": "classes/App-Models-LaravelCache.html#method_forget"
        },                {
            "fqsen": "\\App\\Models\\LaravelCache\u003A\u003Aflush\u0028\u0029",
            "name": "flush",
            "summary": "Removes\u0020all\u0020items\u0020from\u0020the\u0020cache.",
            "url": "classes/App-Models-LaravelCache.html#method_flush"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Message",
            "name": "Message",
            "summary": "Abstract\u0020class\u0020for\u0020messages.",
            "url": "classes/Mve-FcmPhp-Models-Message.html"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Message\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-Message.html#method___construct"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Message\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Get\u0020the\u0020id\u0020of\u0020this\u0020message.",
            "url": "classes/Mve-FcmPhp-Models-Message.html#method_getId"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Message\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Returns\u0020the\u0020message\u0020as\u0020an\u0020array\u0020in\u0020the\u0020format\u0020as\u0020expected\u0020by\u0020the\u0020Google\u0020API.",
            "url": "classes/Mve-FcmPhp-Models-Message.html#method_toArray"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Message\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-Message.html#property_id"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Message\u003A\u003A\u0024body",
            "name": "body",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-Message.html#property_body"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Message\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-Message.html#property_title"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Messaging",
            "name": "Messaging",
            "summary": "Class\u0020for\u0020sending\u0020messages.",
            "url": "classes/Mve-FcmPhp-Models-Messaging.html"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Messaging\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-Messaging.html#method___construct"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Messaging\u003A\u003AcallWithRetryOnExpiredAccessToken\u0028\u0029",
            "name": "callWithRetryOnExpiredAccessToken",
            "summary": "Call\u0020the\u0020Google\u0020API\u0020with\u0020one\u0020retry\u0020in\u0020case\u0020of\u0020expired\u0020access\u0020token.",
            "url": "classes/Mve-FcmPhp-Models-Messaging.html#method_callWithRetryOnExpiredAccessToken"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Messaging\u003A\u003AgetInfo\u0028\u0029",
            "name": "getInfo",
            "summary": "Gets\u0020info\u0020about\u0020a\u0020specific\u0020token.",
            "url": "classes/Mve-FcmPhp-Models-Messaging.html#method_getInfo"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Messaging\u003A\u003AsendToTopic\u0028\u0029",
            "name": "sendToTopic",
            "summary": "Sends\u0020a\u0020message\u0020to\u0020a\u0020topic",
            "url": "classes/Mve-FcmPhp-Models-Messaging.html#method_sendToTopic"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Messaging\u003A\u003AsubscribeToTopic\u0028\u0029",
            "name": "subscribeToTopic",
            "summary": "Subscribe\u0020token\u0020to\u0020topic.",
            "url": "classes/Mve-FcmPhp-Models-Messaging.html#method_subscribeToTopic"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Messaging\u003A\u003AunsubscribeFromTopic\u0028\u0029",
            "name": "unsubscribeFromTopic",
            "summary": "Unsubscribe\u0020tokens\u0020from\u0020topic.",
            "url": "classes/Mve-FcmPhp-Models-Messaging.html#method_unsubscribeFromTopic"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Messaging\u003A\u003AsendAll\u0028\u0029",
            "name": "sendAll",
            "summary": "Send\u0020multiple\u0020messages.",
            "url": "classes/Mve-FcmPhp-Models-Messaging.html#method_sendAll"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Messaging\u003A\u003A_sendAll\u0028\u0029",
            "name": "_sendAll",
            "summary": "Send\u0020multiple\u0020messages\u0020with\u0020an\u0020optional\u0020retry\u0020in\u0020case\u0020of\u0020expired\u0020access\u0020token.",
            "url": "classes/Mve-FcmPhp-Models-Messaging.html#method__sendAll"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Messaging\u003A\u003A\u0024accessTokenHandler",
            "name": "accessTokenHandler",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-Messaging.html#property_accessTokenHandler"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Messaging\u003A\u003A\u0024cache",
            "name": "cache",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-Messaging.html#property_cache"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\Messaging\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-Messaging.html#property_logger"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\SendAllResult",
            "name": "SendAllResult",
            "summary": "A\u0020result\u0020for\u0020multiple\u0020messages.\u0020For\u0020example\u0020used\u0020when\u0020sending\u0020multiple\u0020messages\u0020to\u0020multiple\u0020devices.",
            "url": "classes/Mve-FcmPhp-Models-SendAllResult.html"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\SendAllResult\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-SendAllResult.html#method___construct"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\SendAllResult\u003A\u003A\u0024sent",
            "name": "sent",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-SendAllResult.html#property_sent"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\SendAllResult\u003A\u003A\u0024unregistered",
            "name": "unregistered",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-SendAllResult.html#property_unregistered"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\SendAllResult\u003A\u003A\u0024errors",
            "name": "errors",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-SendAllResult.html#property_errors"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TokenMessage",
            "name": "TokenMessage",
            "summary": "Message\u0020that\u0020is\u0020sent\u0020to\u0020a\u0020specific\u0020token.",
            "url": "classes/Mve-FcmPhp-Models-TokenMessage.html"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TokenMessage\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-TokenMessage.html#method___construct"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TokenMessage\u003A\u003AgetToken\u0028\u0029",
            "name": "getToken",
            "summary": "Returns\u0020the\u0020registration\u0020token.",
            "url": "classes/Mve-FcmPhp-Models-TokenMessage.html#method_getToken"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TokenMessage\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Returns\u0020the\u0020message\u0020as\u0020an\u0020array\u0020in\u0020the\u0020format\u0020as\u0020expected\u0020by\u0020the\u0020Google\u0020API.",
            "url": "classes/Mve-FcmPhp-Models-TokenMessage.html#method_toArray"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TokenMessage\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-TokenMessage.html#property_id"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TokenMessage\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-TokenMessage.html#property_token"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TokenMessage\u003A\u003A\u0024body",
            "name": "body",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-TokenMessage.html#property_body"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TokenMessage\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-TokenMessage.html#property_title"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TopicMessage",
            "name": "TopicMessage",
            "summary": "Message\u0020that\u0020is\u0020sent\u0020to\u0020a\u0020specific\u0020topic.",
            "url": "classes/Mve-FcmPhp-Models-TopicMessage.html"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TopicMessage\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-TopicMessage.html#method___construct"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TopicMessage\u003A\u003AgetTopic\u0028\u0029",
            "name": "getTopic",
            "summary": "Returns\u0020the\u0020topic.",
            "url": "classes/Mve-FcmPhp-Models-TopicMessage.html#method_getTopic"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TopicMessage\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Returns\u0020the\u0020message\u0020as\u0020an\u0020array\u0020in\u0020the\u0020format\u0020as\u0020expected\u0020by\u0020the\u0020Google\u0020API.",
            "url": "classes/Mve-FcmPhp-Models-TopicMessage.html#method_toArray"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TopicMessage\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-TopicMessage.html#property_id"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TopicMessage\u003A\u003A\u0024topic",
            "name": "topic",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-TopicMessage.html#property_topic"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TopicMessage\u003A\u003A\u0024body",
            "name": "body",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-TopicMessage.html#property_body"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models\\TopicMessage\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/Mve-FcmPhp-Models-TopicMessage.html#property_title"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Mve\\FcmPhp\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/mve-fcmphp-models.html"
        },                {
            "fqsen": "\\Mve\\FcmPhp",
            "name": "FcmPhp",
            "summary": "",
            "url": "namespaces/mve-fcmphp.html"
        },                {
            "fqsen": "\\Mve",
            "name": "Mve",
            "summary": "",
            "url": "namespaces/mve.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        }            ]
);
